/*
 * This file is generated by jOOQ.
 */
package docow.jooq;


import java.util.Arrays;
import java.util.List;

import docow.jooq.tables.CaseConfig;
import docow.jooq.tables.CaseDetail;
import docow.jooq.tables.CaseGroup;
import docow.jooq.tables.CaseResult;
import docow.jooq.tables.FlywaySchemaHistory;
import docow.jooq.tables.TestConfig;
import docow.jooq.tables.UserAccount;
import docow.jooq.tables.UserDefineParam;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Docow extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>docow</code>
     */
    public static final Docow DOCOW = new Docow();

    /**
     * The table <code>docow.case_config</code>.
     */
    public final CaseConfig CASE_CONFIG = CaseConfig.CASE_CONFIG;

    /**
     * The table <code>docow.case_detail</code>.
     */
    public final CaseDetail CASE_DETAIL = CaseDetail.CASE_DETAIL;

    /**
     * The table <code>docow.case_group</code>.
     */
    public final CaseGroup CASE_GROUP = CaseGroup.CASE_GROUP;

    /**
     * The table <code>docow.case_result</code>.
     */
    public final CaseResult CASE_RESULT = CaseResult.CASE_RESULT;

    /**
     * The table <code>docow.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>docow.test_config</code>.
     */
    public final TestConfig TEST_CONFIG = TestConfig.TEST_CONFIG;

    /**
     * The table <code>docow.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * The table <code>docow.user_define_param</code>.
     */
    public final UserDefineParam USER_DEFINE_PARAM = UserDefineParam.USER_DEFINE_PARAM;

    /**
     * No further instances allowed
     */
    private Docow() {
        super("docow", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            CaseConfig.CASE_CONFIG,
            CaseDetail.CASE_DETAIL,
            CaseGroup.CASE_GROUP,
            CaseResult.CASE_RESULT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            TestConfig.TEST_CONFIG,
            UserAccount.USER_ACCOUNT,
            UserDefineParam.USER_DEFINE_PARAM);
    }
}
